### ISSUE TITLE
WPA Supplicant & Networkd relationship unclear

### ISSUE THREAD

**Issue by 17twenty** [gumstix/meta-gumstix-extras#16]
I've been piecing together the different sources and they still reference older iwlist and ifconfig for configuration.

I currently have a gumstix with the following contents for /etc/wpa_supplicant/wpa_supplicant-wlan0.conf

network={
  ssid="testfactory"
  key_mgmt=WPA-PSK
  proto=WPA2
  psk="testkey"
}

I was under the assumption that by simply doing a systemctl enable wpa_supplicant@wlan0 that this should work but it still shows:

$ ifconfig
...
wlan0     Link encap:Ethernet  HWaddr 00:19:88:52:78:4F
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:20 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

What is the correct way to work with networkd on the gumstix? I'm working from the latest Yocto build so 3.17.8-custom kernel.

**Comment by ashcharles** [comment]
Your modification to the wpa_supplicant-wlan0.conf looks good to
automatically connect to a "testfactory" access point. In fact, you should
not need to manually enable wpa_supplicant@wlan0---it should already be
running.  Rebooting the system or restarting the daemon may be needed
though to the settings to 'take'.
The instructions are in need of an update!  I'd suggest the following
commands to understand the current state of connection.
$ ifconfig wlan0
$ iw wlan0 info
$ iw wlan0 link
What behaviour are you seeing on boot?

**Comment by 17twenty** [comment]
Thanks for the quick reply - this is the output we're seeing. 
We're currently in NZ but don't imagine that should cause any issues for wpa_supplicant?

[ 2142.740875] cfg80211: Calling CRDA to update world regulatory domain
[ 2145.958984] cfg80211: Calling CRDA for country: GB
$ systemctl status wpa_supplicant@wlan0.service -l
● wpa_supplicant@wlan0.service - WPA supplicant daemon (interface-specific version)
   Loaded: loaded (/lib/systemd/system/wpa_supplicant@.service; enabled)
   Active: active (running) since Thu 2015-03-05 06:08:35 UTC; 16s ago
 Main PID: 3349 (wpa_supplicant)
   CGroup: /system.slice/system-wpa_supplicant.slice/wpa_supplicant@wlan0.service
           └─3349 /usr/sbin/wpa_supplicant -c/etc/wpa_supplicant/wpa_supplicant-wlan0.conf -iwlan0

Mar 05 06:08:35 littlenick systemd[1]: Started WPA supplicant daemon (interface-specific version).
Mar 05 06:08:35 littlenick wpa_supplicant[3349]: Libgcrypt warning: missing initialization - please fix the application
[ 2161.607879] cfg80211: Calling CRDA to update world regulatory domain
[ 2162.528472] cfg80211: Calling CRDA to update world regulatory domain
root@littlenick:~# [ 2165.808349] cfg80211: Calling CRDA to update world regulatory domain
[ 2189.978546] cfg80211: Calling CRDA to update world regulatory domain
[ 2193.248352] cfg80211: Calling CRDA for country: GB


root@littlenick:~# ifconfig wlan0
wlan0     Link encap:Ethernet  HWaddr 00:19:88:52:78:4F  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:15 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:1 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1695 (1.6 KiB)  TX bytes:0 (0.0 B)

root@littlenick:~# iw wlan0 info
Interface wlan0
        ifindex 3
        wdev 0x1
        addr 00:19:88:52:78:4f
        type managed
        wiphy 0
root@littlenick:~#  iw wlan0 link
Not connected.

----
It sits their spewing out the Calling CRDA notifications but never establishes a link (as you can see).

**Comment by 17twenty** [comment]
As an aside, I *can* use the iw dev wlan0 scan to find the correct SSID... it just won't connect and spawn udhcpc or anything.

$ iw dev wlan0 scan | grep SSID
        SSID: testfactory
        SSID: CPP
        SSID: TrafficMate

$ iw wlan0 link
Not connected.

**Comment by ashcharles** [comment]
This isn't working on all boards for me either.  Their appears to be some
problem authenticating---I even saw an Overo (older W2CBW003 network
module) connect then immediately disconnect---it looked like the chip opted
to DEAUTH.  A couple debugging things I tried:
$ systemctl status wpa_supplicant@wlan0
---> to pick up configuration errors etc.
Edit /lib/systemd/system/wpa_supplicant@.service to add '-dd' to the
ExecStart line then
$ systemctl daemon-reload
$ systemctl restart wpa_supplicant@wlan0
$ journal -u wpa_supplicant@wlan0 -f
--> follow debugging output.

**Comment by 17twenty** [comment]
And to help any one else suffering this issue (which we can hopefully resolve!) - this is the output from running wpa_supplicant standalone outside of networkd:

$ /usr/sbin/wpa_supplicant -c/etc/wpa_supplicant/wpa_supplicant-oot@littlenick:~# /usr/sbin/wpa_supplicant -c/etc/wpa_supplicant/
Successfully initialized wpa_supplicant
wlan0: CTRL-EVENT-SCAN-STARTED 
wlan0: Trying to associate with 88:43:e1:65:87:2a (SSID='testfactory' freq=2412 MHz)
[  243.080902] cfg80211: Calling CRDA to update world regulatory domain
wlan0: Associated with 88:43:e1:65:87:2a
wlan0: CTRL-EVENT-DISCONNECTED bssid=88:43:e1:65:87:2a reason=6
wlan0: WPA: 4-Way Handshake failed - pre-shared key may be incorrect
wlan0: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="testfactory" auth_failures=1 duration=10 reason=WRONG_KEY
[  246.336791] cfg80211: Calling CRDA for country: GB
wlan0: CTRL-EVENT-SCAN-STARTED 
wlan0: CTRL-EVENT-SCAN-STARTED 
wlan0: CTRL-EVENT-SCAN-STARTED 
wlan0: CTRL-EVENT-SSID-REENABLED id=0 ssid="testfactory"
wlan0: Trying to associate with 88:43:e1:65:87:2a (SSID='testfactory' freq=2412 MHz)
wlan0: Associated with 88:43:e1:65:87:2a
wlan0: CTRL-EVENT-DISCONNECTED bssid=88:43:e1:65:87:2a reason=6
[  262.088378] cfg80211: Calling CRDA to update world regulatory domain
wlan0: CTRL-EVENT-SCAN-STARTED 
wlan0: Trying to associate with 88:43:e1:65:87:2a (SSID='testfactory' freq=2412 MHz)
[  263.008636] cfg80211: Calling CRDA to update world regulatory domain
wlan0: Associated with 88:43:e1:65:87:2a
wlan0: CTRL-EVENT-DISCONNECTED bssid=88:43:e1:65:87:2a reason=6
[  266.297729] cfg80211: Calling CRDA to update world regulatory domain
wlan0: CTRL-EVENT-SCAN-STARTED 
wlan0: Trying to associate with 88:43:e1:65:87:2a (SSID='testfactory' freq=2412 MHz)
[  267.208587] cfg80211: Calling CRDA to update world regulatory domain
wlan0: Associated with 88:43:e1:65:87:2a
wlan0: CTRL-EVENT-DISCONNECTED bssid=88:43:e1:65:87:2a reason=6
wlan0: WPA: 4-Way Handshake failed - pre-shared key may be incorrect
wlan0: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="testfactory" auth_failures=2 duration=20 reason=WRONG_KEY
wlan0: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="testfactory" auth_failures=3 duration=30 reason=CONN_FAILED
[  270.378387] cfg80211: Calling CRDA for country: GB
wlan0: CTRL-EVENT-SCAN-STARTED 
wlan0: CTRL-EVENT-SCAN-STARTED

**Comment by 17twenty** [comment]
$ journalctl -u wpa_supplicant@wlan0 -f
-- Logs begin at Thu 2015-03-05 07:45:38 UTC. --
Mar 05 07:55:08 littlenick wpa_supplicant[2322]: wlan0: Selecting BSS from priority group 0
Mar 05 07:55:08 littlenick wpa_supplicant[2322]: wlan0: 0: 88:43:e1:65:87:2a ssid='testfactory' wpa_ie_len=26 rsn_ie_len=24 caps=0x431 level=-49 wps
Mar 05 07:55:08 littlenick wpa_supplicant[2322]: wlan0:    skip - disabled temporarily for 13 second(s)
Mar 05 07:55:08 littlenick wpa_supplicant[2322]: wlan0: 1: dc:9f:db:9c:1a:52 ssid='CPP' wpa_ie_len=0 rsn_ie_len=20 caps=0x431 level=-62
Mar 05 07:55:08 littlenick wpa_supplicant[2322]: wlan0:    skip - disabled temporarily for 13 second(s)
Mar 05 07:55:08 littlenick wpa_supplicant[2322]: wlan0: 2: 32:cd:a7:27:89:c9 ssid='DIRECT-F3M283x Series' wpa_ie_len=0 rsn_ie_len=20 caps=0x411 level=-63 wps
Mar 05 07:55:08 littlenick wpa_supplicant[2322]: wlan0:    skip - disabled temporarily for 13 second(s)
Mar 05 07:55:08 littlenick wpa_supplicant[2322]: wlan0: 3: dc:9f:db:9c:1a:51 ssid='CPP' wpa_ie_len=0 rsn_ie_len=20 caps=0x431 level=-81
Mar 05 07:55:08 littlenick wpa_supplicant[2322]: wlan0:    skip - disabled temporarily for 13 second(s)
Mar 05 07:55:08 littlenick wpa_supplicant[2322]: wlan0: 4: 84:c9:b2:09:20:5a ssid='Searanger' wpa_ie_len=26 rsn_ie_len=24 caps=0xc11 level=-84
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0:    skip - disabled temporarily for 13 second(s)
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: No suitable network found
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Setting scan request: 5.000000 sec
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Starting AP scan for wildcard SSID
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Add radio work 'scan'@0xf6060
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: First radio work item in the queue - schedule start immediately
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Starting radio work 'scan'@0xf6060 after 0.000061 second wait
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: nl80211: scan request
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: nl80211: Scan SSID - hexdump_ascii(len=0): [NULL]
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: Scan requested (ret=0) - scan timeout 30 seconds
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: nl80211: Event message available
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: nl80211: Drv Event 33 (NL80211_CMD_TRIGGER_SCAN) received for wlan0
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: nl80211: Scan trigger
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Event SCAN_STARTED (49) received
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Own scan request started a scan in 0.000183 seconds
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: CTRL-EVENT-SCAN-STARTED
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: 4: 84:c9:b2:09:20:5a ssid='Searanger' wpa_ie_len=26 rsn_ie_len=24 caps=0xc11 level=-84
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0:    skip - disabled temporarily for 8 second(s)
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: No suitable network found
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Setting scan request: 5.000000 sec
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Starting AP scan for wildcard SSID
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Add radio work 'scan'@0xf6060
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: First radio work item in the queue - schedule start immediately
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Starting radio work 'scan'@0xf6060 after 0.000061 second wait
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: nl80211: scan request
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: nl80211: Scan SSID - hexdump_ascii(len=0): [NULL]
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: Scan requested (ret=0) - scan timeout 30 seconds
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: nl80211: Event message available
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: nl80211: Drv Event 33 (NL80211_CMD_TRIGGER_SCAN) received for wlan0
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: nl80211: Scan trigger
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Event SCAN_STARTED (49) received
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Own scan request started a scan in 0.000153 seconds
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: CTRL-EVENT-SCAN-STARTED
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: nl80211: Event message available
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: nl80211: Drv Event 34 (NL80211_CMD_NEW_SCAN_RESULTS) received for wlan0
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: nl80211: New scan results available
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: nl80211: Scan probed for SSID ''
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: nl80211: Scan included frequencies: 2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472 2484
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Event SCAN_RESULTS (3) received
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Scan completed in 0.806610 seconds
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: nl80211: Received scan results (5 BSSes)
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: BSS: Start scan result update 10
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: BSS: last_scan_res_used=5/32
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: New scan results available (own=1 ext=0)
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: WPS: Unknown Vendor Extension (Vendor ID 9442)
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: WPS: Unknown Vendor Extension (Vendor ID 9442)
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: WPS: Unknown Vendor Extension (Vendor ID 9442)
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: WPS: Unknown Vendor Extension (Vendor ID 9442)
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: WPS: AP[0] 88:43:e1:65:87:2a type=0 tries=0 last_attempt=-1 sec ago blacklist=0
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: WPS: AP[1] 32:cd:a7:27:89:c9 type=1 tries=0 last_attempt=-1 sec ago blacklist=0
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Radio work 'scan'@0xf6060 done in 0.808381 seconds
Mar 05 07:55:20 littlenick wpa_supplicant[2322]: wlan0: Selecting BSS from priority group 0
^C
root@littlenick:~# [  596.539123] cfg80211: Calling CRDA to update world regulatory domain



Kind of glad to see you can reproduce the issue - suggestions welcome on fixes. Kernel compile time issue?

**Comment by ashcharles** [comment]
It doesn't look like a kernel issue as I tested three different Overo COMs
with three different wireless chips (W2CBW003: non-'plasma', W2CBW0015:
'plasma', and wl1831: to-be-announced) with a console image both connecting
to an unsecured access point and a WPA2 secured access point.  All worked
correctly with this image [1].

My network config section for wpa2 a la [2].
network={
      ssid="gumstix"
      proto=WPA2
      key_mgmt=WPA-PSK
      pairwise=CCMP TKIP
      group=CCMP TKIP
      scan_ssid=1
      psk="this-is-a-fake-password"
      priority=10
}

This makes me suspect that there is some bad interaction between network
manager and systemd-network about who's running the show.

[1] https://catalina.gumstix.com/binaries/1511/
[2]
https://github.com/gumstix/meta-gumstix-extras/blob/dizzy/recipes-connectivity/wpa-supplicant/files/wpa_supplicant.conf

**Comment by ashcharles** [comment]
As suspected, network-manager and systemd-networkd seem to be fighting.  If
I disable the wlan0 instance of wpa_supplicant, I can connect to access
points (secure and otherwise) using the network manager (wpa_supplicant is
triggered under the hood using dbus-activation):
$ systemctl disable wpa_supplicant@wlan0
$ systemctl stop wpa_supplicant@wlan0

Likewise, I can disable Network Manager instead and control everything
through /etc/wpa_supplicant/wpa_supplicant-wlan0.conf (which means the GUI
network manager doesn't appear)
$ systemctl disable NetworkManager
$ systemctl stop NetworkManager
$ systemctl enable wpa_supplicant@wlan0
$ systemctl start wpa_supplicant@wlan0

**Comment by 17twenty** [comment]
My hardware is currently under test for USB issues (devices going down and coming back up) but can you confirm that this affects gumstix-console-image as NetworkManager is normally a GUI thing so wouldn't have thought that would be installed - esp as DBus is normally dependent on a graphics server?

**Comment by ashcharles** [comment]
To confirm, I don't have an issue connecting to networks on a console image.

**Comment by ashcharles** [comment]
https://github.com/gumstix/meta-gumstix-extras/commit/e04824495bd638527509868418677935d7bab5e2
